




#' A sampler for a linear model with independent Normal-Gamma priors
#'
#' The sampler uses independent Normal-Gamma priors to estimate a linear model. The function is
#' meant intended as an illustration on using the \code{\link{beta_sampler}} and \code{\link{sigma_sampler}}
#' classes.
#'
#' @param Y numeric \eqn{tt * n} by \eqn{1} matrix containing the dependent variables.
#' @param tt single number greater or equal to 1. Denotes the number of time observations.
#' @param X numeric \eqn{tt * n} by \eqn{k_1} design matrix of independent variables.
#' @param niter single number greater or equal to 1, indicating the total number of draws.
#' Will be automatically coerced to integer. The default value is 1000.
#' @param nretain single number greater or equal to 0, indicating the number of draws
#' kept after the burn-in. Will be automatically coerced to integer. The default value is 500.
#' @param beta_prior List of priors for the slope coefficients \eqn{\beta},
#' generated by the smart constructor \code{\link{beta_priors}}.
#' @param sigma_prior List of priors for the error variance \eqn{\sigma^2},
#' generated by the smart constructor \code{\link{sigma_priors}}
#'
#' @export
#'
#' @examples
#' n = 20; tt = 10; k = 3
#' X = matrix(stats::rnorm(n*tt*k),n*tt,k)
#' Y = X %*% c(1,0,-1) + stats::rnorm(n*tt,0,.5)
#' res = normalgamma(Y,tt,X)
normalgamma <- function(Y, tt, X = matrix(1,nrow(Y),1), niter = 1000, nretain = 250,
                 beta_prior = beta_priors(k = ncol(X)),sigma_prior = sigma_priors()) {
  k = ncol(X); n <- nrow(X) / tt
  ndiscard <- niter - nretain

  # save the posterior draws here
  if (is.null(colnames(X))) {colnames(X) = paste0("X",1:k)}
  varnames = colnames(X)
  postb <- matrix(0, k, nretain); rownames(postb) <- colnames(X)
  posts <- matrix(0, 1, nretain); rownames(posts) = "sigma"

  sampler_beta = beta_sampler$new(beta_prior)
  sampler_sigma = sigma_sampler$new(sigma_prior)

  ### Gibbs sampling
  pb <- utils::txtProgressBar(min = 0, max = niter, style = 3)
  for (iter in 1:niter) {
    # draw beta
    sampler_beta$sample(Y,X,sampler_sigma$curr_sigma)
    curr.xb <- X %*% sampler_beta$curr_beta

    # draw sigma
    sampler_sigma$sample(Y,curr.xb)

    # we are past the burn-in, save the draws
    if (iter > ndiscard) {
      s <- iter - ndiscard
      postb[, s] <- sampler_beta$curr_beta
      posts[s] <- sampler_sigma$curr_sigma
    }
    utils::setTxtProgressBar(pb,iter)
  }
  close(pb)

  ret = list(Y = Y, X = X,
             postb = postb, posts = posts,
             beta_prior = beta_prior,sigma_prior = sigma_prior,
             param = list(niter = niter, nretain = nretain)
  )
  class(ret) = "estimateW"
  return(ret)
}

#' A sampler for the Spatial Durbin Model with exogeneous spatial weight matrix.
#'
#' The sampler uses independent an Normal-Gamma prior for the slope and variance parameters,
#' as well as the four-parameter prior for the spatial autoregressive parameter. The function is
#' meant intended as an illustration on using the \code{\link{beta_sampler}}, \code{\link{sigma_sampler}},
#' and \code{\link{rho_sampler}} classes.
#'
#' @param Y numeric \eqn{tt * n} by \eqn{1} matrix containing the dependent variables.
#' @param tt single number greater or equal to 1. Denotes the number of time observations.
#' @param W numeric, non-negative \eqn{n} by \eqn{n} exogenous spatial weight matrix. Must have
#' zeros on the main diagonal.
#' @param X numeric \eqn{tt * n} by \eqn{k_1} design matrix of independent variables.
#' @param Z An \eqn{tt * n} by \eqn{k_3} design matrix of independent variables.
#' @param niter single number greater or equal to 1, indicating the total number of draws.
#' Will be automatically coerced to integer. The default value is 1000.
#' @param nretain single number greater or equal to 0, indicating the number of draws
#' kept after the burn-in. Will be automatically coerced to integer. The default value is 500.
#' @param rho_prior List of priors for estimating \eqn{\rho}, generated by the smart constructor \code{\link{rho_priors}}
#' @param beta_prior List of priors for the slope coefficients \eqn{\beta},
#' generated by the smart constructor \code{\link{beta_priors}}.
#' @param sigma_prior List of priors for the error variance \eqn{\sigma^2},
#' generated by the smart constructor \code{\link{sigma_priors}}
#'
#' @export
#'
#' @examples
#' n = 20; tt = 10
#' dgp_dat = sim_dgp(n =n, tt = tt, rho = .5, beta1 = c(.5,1),beta2 = c(-1,.5),
#'                   beta3 = c(1.5), sigma2 = .5)
#' res = sdm(Y = dgp_dat$Y,tt = tt, W = dgp_dat$W,X = dgp_dat$X,Z = dgp_dat$Z,niter = 200,nretain = 100)
sdm <- function(Y, tt, W, X = matrix(0,nrow(Y),0),Z = matrix(1,nrow(Y),1), niter = 1000, nretain = 250,
                rho_prior = rho_priors(),beta_prior = beta_priors(k = ncol(X)*2 + ncol(Z)),
                sigma_prior = sigma_priors()) {
  if (ncol(X) == 0 && ncol(Z) == 0) {stop("Error: At least either X or Z matrix have to be provided.")}
  origX = X

  smallk = ncol(X)
  if (smallk>0 && is.null(colnames(X))) {
    colnames(X) = paste0("X",1:smallk)
  }
  k_dum = ncol(Z)
  if (k_dum>0 && is.null(colnames(Z))) {
    colnames(Z) = paste0("Z",1:k_dum)
  }
  if (smallk>0) {varnames = c(colnames(X), paste0("W_",colnames(X)))} else {varnames = c()}
  if (k_dum > 0) varnames = c(varnames,colnames(Z))

  ndiscard <- niter - nretain
  k <- smallk*2 + k_dum
  n <- nrow(X) / tt

  # map variable positions for spatial effects
  ind_baseX = ind_WX = ind_lagFX = c()
  if (smallk > 0) {
    ind_baseX = c(1:smallk)
    # the columns of XX that are spatially lagged
    ind_WX = c(1:smallk) + smallk
    # the spatial FX corresponding to these
    ind_lagFX = 1:smallk
  }
  if (k_dum > 0) {ind_baseX = c(ind_baseX,(2*smallk + 1):k)}

  # save the posterior draws here
  postb <- matrix(0, k, nretain)
  rownames(postb) <- varnames
  posts <- matrix(0, 1, nretain); rownames(posts) = "sigma"
  postr <- matrix(0, 1, nretain); rownames(postr) = "rho"

  post.direct <- matrix(0, smallk + k_dum, nretain)
  post.indirect <- matrix(0, smallk + k_dum, nretain)
  post.total <- matrix(0, smallk + k_dum, nretain)
  rownames(post.direct) <- rownames(post.indirect) <- rownames(post.total) <- varnames[ind_baseX]

  # initilize wdraws
  curr.WX = as.matrix(kronecker(Matrix::.sparseDiagonal(tt),W) %*% X)
  tX = cbind(X,curr.WX,Z)
  tY <- matrix(Y, n, tt)
  tAy <- matrix(0, n, tt)

  sampler_beta = beta_sampler$new(beta_prior)
  sampler_sigma = sigma_sampler$new(sigma_prior)
  if (rho_prior$use_griddy_gibbs) {
    sampler_rho <- rho_sampler$new(rho_prior)
  } else {
    sampler_rho = rho_samplerMH$new(rho_prior)
  }
  sampler_rho$setW(W)

  ### Gibbs sampling
  pb <- utils::txtProgressBar(min = 0, max = niter, style = 3)
  for (iter in 1:niter) {
    Ay <- matrix(sampler_rho$curr_A %*% tY, n * tt, 1)

    # draw beta
    sampler_beta$sample(Ay,tX,sampler_sigma$curr_sigma)
    curr.xb <- tX %*% sampler_beta$curr_beta
    curr.txb <- matrix(curr.xb, n, tt)

    # draw sigma
    sampler_sigma$sample(Ay,curr.xb)

    if (rho_prior$use_griddy_gibbs) {
      sampler_rho$sample(tY,curr.txb,sampler_sigma$curr_sigma)
    } else {
      sampler_rho$sample(tY,curr.txb,sampler_sigma$curr_sigma)
      if (iter > (ndiscard / 2)) {
        sampler_rho$stopMHtune()
      }
    }

    # we are past the burn-in, save the draws
    if (iter > ndiscard) {
      s <- iter - ndiscard
      postb[, s] <- sampler_beta$curr_beta
      posts[s] <- sampler_sigma$curr_sigma
      postr[s] <- sampler_rho$curr_rho
    }
    utils::setTxtProgressBar(pb,iter)
  }
  close(pb)

  ret = list(Y = Y, X = X, Z = Z, W = W,
             postb = postb, posts = posts,postr = postr,
             beta_prior = beta_prior,sigma_prior = sigma_prior,
             param = list(niter = niter, nretain = nretain)
  )
  class(ret) = "estimateW"
  return(ret)
}


