# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AinvUpdate_fast <- function(ch_ind, diff, AI) {
    .Call('_estimateW_AinvUpdate_fast', PACKAGE = 'estimateW', ch_ind, diff, AI)
}

#' Function to calculate error
NULL

#' Function to calculate posterior probality
NULL

#' A fast sampling step implemented in C++ for updating the spatial weight matrix.
#'
#' This function is intended to be called from the R6 class \code{\link{W_sampler}}.
#'
#' @param Y The \eqn{n} by \eqn{tt} matrix of responses
#' @param curr_sigma The variance parameter \eqn{\sigma^2}
#' @param mu The \eqn{n} by \eqn{tt} matrix of means.
#' @param lag_mu \eqn{n} by \eqn{tt} matrix of means that will be spatially lagged with
#' the estimated \eqn{W}. Defaults to a matrix with zero elements.
#' @param W_prior The current \code{\link{W_priors}}
#' @param curr_W binary \eqn{n} by \eqn{n} spatial connectivity matrix \eqn{\Omega}
#' @param curr_w Row-standardized \eqn{n} by \eqn{n} spatial weight matrix \eqn{W}
#' @param curr_A The current spatial projection matrix \eqn{I - \rho W}.
#' @param curr_AI The inverse of \code{curr_A}
#' @param curr_logdet The current log-determinant of \code{curr_A}
#' @param curr_rho single number between -1 and 1 or NULL, depending on whether the sampler updates
#' the spatial autoregressive parameter \eqn{\rho}. Set while invoking \code{initialize}
#' or using the function \code{set_rho}.
#' @param nr_neighbors_prior An \eqn{n} dimensional vector of prior weights on the number of neighbors
#' (i.e. the row sums of the adjacency matrix \eqn{\Omega}), where the first element denotes the prior probability
#' of zero neighbors and the last those of \eqn{n-1}. A prior using only fixed inclusion probabilities
#' for the entries in \eqn{\Omega} would be an \eqn{n} dimensional vector of \eqn{1/n}. Defaults to
#' a \code{\link{bbinompdf}} prior, with prior parameters \eqn{a = 1}, \eqn{b = 1}.
#' @param symmetric Binary value. Should the estimated adjacency matrix \eqn{\Omega} be symmetric (default: FALSE)?
#' if TRUE: \eqn{\Omega} is forced symmetric; if FALSE: \eqn{\Omega} not necessarily symmetric.
#' @param spatial_error Should a spatial error model be constructed? Defaults to \code{FALSE}.
#' @param row_standardized Binary value. Should the estimated \eqn{W} matrix be row-standardized (default: TRUE)?
#' if TRUE: row-stochastic \eqn{W}; if FALSE: \eqn{W} not row-standardized.
#'
#' @export
sampleW_fast <- function(Y, curr_sigma, mu, lag_mu, W_prior, curr_W, curr_w, curr_A, curr_AI, curr_logdet, curr_rho, nr_neighbors_prior, symmetric, spatial_error, row_standardized) {
    .Call('_estimateW_sampleW_fast', PACKAGE = 'estimateW', Y, curr_sigma, mu, lag_mu, W_prior, curr_W, curr_w, curr_A, curr_AI, curr_logdet, curr_rho, nr_neighbors_prior, symmetric, spatial_error, row_standardized)
}

