
#' A sampler for estimating the W matrix in a SDM type model
#'
#' The model takes the form \eqn{Y = X \beta_1 + f(\Omega)X \beta_2 + Z \beta_3 +  \epsilon}, with \eqn{\epsilon \sim N(0,\sigma^2)}
#'
#' @param Y An \eqn{tt n x 1} matrix of dependent variables
#' @param tt Number of time observations
#' @param X An \eqn{tt n x q_x} matrix of independent variables
#' @param Z An \eqn{tt n x q_k} matrix of independent variables
#' @param niter Total number of iterations
#' @param nretain Number of iterations to retain (must be smaller than niter)
#' @param W_prior List of priors for estimating \eqn{W}, generated by \code{\link{W_priors}}
#' @param beta_prior List of priors for the slope coefficients \eqn{\beta}, generated by \code{\link{beta_priors}}
#' @param sigma_prior List of priors for the error variance \eqn{\sigma^2}, generated by \code{\link{sigma_priors}}
#'
#' @return List with posterior samples for \eqn{\beta}, \eqn{\sigma^2}, \eqn{w}.
#' @export slxw
#'
#' @examples
#' n = 20; tt = 10
#' dgp_dat = sim_slxw(n =20, tt = 10, beta1 = c(1,-1), beta2 = c(0,.5), beta3 = c(.2), sigma2 = .5)
#' res = slxw(Y = dgp_dat$Y,tt = tt,X = dgp_dat$X,Z = dgp_dat$Z,niter = 20,nretain = 10)
slxw <- function(Y, tt, X = matrix(0,nrow(Y),0),Z = matrix(1,nrow(Y),1), niter = 1000, nretain = 250,
                 W_prior = W_priors(n = nrow(Y)/tt),
                 beta_prior = beta_priors(k = ncol(X)*2 + ncol(Z)),sigma_prior = sigma_priors()) {
  if (ncol(X) == 0 && ncol(Z) == 0) {stop("Error: At least either X or Z matrix have to be provided.")}
  origX = X

  smallk = ncol(X)
  if (smallk>0 && is.null(colnames(X))) {
    colnames(X) = paste0("X",1:smallk)
  }
  k_dum = ncol(Z)
  if (k_dum>0 && is.null(colnames(Z))) {
    colnames(Z) = paste0("Z",1:k_dum)
  }
  if (smallk>0) {varnames = c(colnames(X), paste0("W_",colnames(X)))} else {varnames = c()}
  if (k_dum > 0) varnames = c(varnames,colnames(Z))

  ndiscard <- niter - nretain
  k <- smallk*2 + k_dum
  n <- nrow(X) / tt

  # map variable positions for spatial effects
  ind_baseX = ind_WX = ind_lagFX = c()
  if (smallk > 0) {
    ind_baseX = c(1:smallk)
    # the columns of XX that are spatially lagged
    ind_WX = c(1:smallk) + smallk
    # the spatial FX corresponding to these
    ind_lagFX = 1:smallk
  }
  if (k_dum > 0) {ind_baseX = c(ind_baseX,(2*smallk + 1):k)}

  # save the posterior draws here
  postb <- matrix(0, k, nretain)
  rownames(postb) <- varnames
  posts <- matrix(0, 1, nretain); rownames(posts) = "sigma"
  postw <- array(0, c(n, n, nretain))
  postwprob <- array(0, c(n, n, nretain))

  # initilize wdraws
  curr.wdraws = init_sampler_W(W_prior,rho = NULL)

  curr.WX = as.matrix(kronecker(Matrix::.sparseDiagonal(tt),curr.wdraws$curr.w) %*% X)
  tX = cbind(X,curr.WX,Z)
  tY <- matrix(Y, n, tt)
  curr.txb1 = curr.txb2 = matrix(0,n,tt)
  curr.beta <- solve(crossprod(tX)) %*% crossprod(tX, Y)
  curr.sigma <- as.double(crossprod(Y - tX %*% curr.beta)) / (tt * n - k)

  ### Gibbs sampling
  pb <- utils::txtProgressBar(min = 0, max = niter, style = 3)
  for (iter in 1:niter) {

    # draw beta
    # e1 = try({
    V <- solve(beta_prior$beta_var_prior_inv + 1 / curr.sigma * crossprod(tX))
    b <- V %*% (beta_prior$beta_var_prior_inv %*% beta_prior$beta_mean_prior + 1 / curr.sigma * crossprod(tX, Y))
    # curr.beta = mvrnorm(1,b,V)
    curr.beta <- b + t(chol(V)) %*% stats::rnorm(k)
    curr.xb <- tX %*% curr.beta
    curr.txb <- matrix(curr.xb, n, tt)
    if (smallk > 0) {
      curr.txb1 = matrix(tX[,-ind_WX] %*% curr.beta[-ind_WX],n,tt)
      curr.txb2 = matrix(X %*% curr.beta[ind_WX],n,tt)
    } else {
      curr.txb1 = matrix(curr.xb,n,tt)
    }

    # draw sigma
    curr.ESS <- crossprod(Y - curr.xb)
    curr.sigma <- 1 / stats::rgamma(1, sigma_prior$sigma_rate_prior + (tt * n) / 2, sigma_prior$sigma_shape_prior + as.double(curr.ESS) / 2)

    # Gibbs step for W - element-wise
    # curr.txb = matrix(curr.xb,n,tt)
    curr.wdraws = sample_W(tY = tY,curr.txb1 = curr.txb1,
                           curr.txb2 = curr.txb2,
                           curr.sigma = curr.sigma,
                           W_prior = W_prior,wdraws = curr.wdraws,curr.rho = NULL)

    curr.WX = as.matrix(kronecker(Matrix::.sparseDiagonal(tt),curr.wdraws$curr.w) %*% X)
    tX = cbind(X,curr.WX,Z)

    # we are past the burn-in, save the draws
    if (iter > ndiscard) {
      s <- iter - ndiscard
      postb[, s] <- as.matrix(curr.beta)
      posts[s] <- curr.sigma
      postw[, , s] <- curr.wdraws$curr.w
    }
    utils::setTxtProgressBar(pb,iter)
  }
  close(pb)

  ret = list( Y = Y, X = X,Z = Z,
             postb = postb, posts = posts, postw = postw,
             W_prior = W_prior,
             beta_prior = beta_prior,sigma_prior = sigma_prior,
             param = list(niter = niter, nretain = nretain)
  )
  class(ret) = "estimateW"
  return(ret)
}
